version: '3.7'

services:

  cockroach:
    container_name: cockroach
    image: cockroachdb/cockroach:v21.1.7
    restart: unless-stopped
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
